
export default {
    TODO_GET_LIST:"GET_LIST",
    TODO_DELETE_ : "DELETE",
    TODO_SHOW_LOADER : "SHOW_LOADER",
    TODO_HIDE_LOADER : "HIDE_LOADER",
    TODO_REGISTER_ERROR : "ERROR_MESSAGE",
    TODO_HANDLE_FORM_DATA : "HANDLE_FORM_DATA",
    TODO_UPDATE_FORM_FIELD : "UPDATE_FORM_FIELD",
    TODO_EMPTY_FORM_FIELD : "EMPTY_FORM_FIELD",
    TODO_PREPOPULATE_EDIT : "PREPOPULATE_FORM_FIELD"
}